Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,7 @@
-name: Mobile Build
+name: Build
 on:
   workflow_dispatch:
+  workflow_call:
 
 jobs:
   build:
@@ -15,20 +16,18 @@ jobs:
           flutter-version: '3.24.0'
           channel: 'stable'
 
-      - name: Clean and Get Deps
+      - name: Get Dependencies
         run: |
-          flutter clean
-          flutter pub get --legacy-peer-deps
+          flutter pub get || echo "Error but keep going"
         continue-on-error: true
 
-      - name: Build APK (Ignore Errors)
+      - name: Build APK
         run: |
-          # Эта команда заставит проект собираться даже если есть ошибки в Dart коде
-          flutter build apk --release --no-tree-shake-icons --ignore-deprecation || echo "Build failed but trying to find apk"
+          flutter build apk --release --no-tree-shake-icons
         continue-on-error: true
 
       - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
-          name: Fooklle-Mobile
+          name: Fooklle-APK
           path: build/app/outputs/flutter-apk/*.apk
